sonar.projectKey=mahdirazzaque_azan-dashboard-local
sonar.organization=mahdirazzaque
sonar.host.url=https://sonarcloud.io

sonar.sources=.
sonar.sourceEncoding=UTF-8

# --- Refined Exclusions ---
# We exclude the .config folder itself, git, and common heavy folders
sonar.exclusions=../node_modules/**, ../dist/**, ../build/**, ../.next/**, ../.git/**, ../venv/**, ../__pycache__/**, ../.pytest_cache/**, ../*.log

# --- Language Specifics ---
# Helps the JS sensor not get lost in non-existent TS configs
sonar.javascript.environments=browser, node

# --- Python Specifics ---
# If you have a specific python version
sonar.python.version=3.10