name: Bandit
on:
  pull_request:
    branches: [main]
    paths:
      - 'src/microservices/**'
  workflow_dispatch:
  workflow_call:

jobs:
  bandit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install and run Bandit
        run: |
          pip install bandit==1.8.3
          bandit -r src/microservices/tts/ -f json
