name: Hadolint

on:
  pull_request:
    branches: [main]
  workflow_dispatch:
  workflow_call:

jobs:
  hadolint:
    name: Lint Dockerfile
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for Docker changes
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            docker:
              - 'docker/**'
              - '.github/workflows/hadolint.yml'

      - name: Run Hadolint
        if: steps.changes.outputs.docker == 'true'
        uses: hadolint/hadolint-action@v3.3.0
        with:
          dockerfile: docker/Dockerfile
