name: Linting

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  workflow_call:

jobs:
  lint:
    name: Run ESLint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for code changes
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            code:
              - 'src/**'
              - 'client/**'
              - 'package.json'
              - 'package-lock.json'
              - '.config/eslint*'
              - '.github/workflows/lint.yml'

      - name: Setup Node.js
        if: steps.changes.outputs.code == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        if: steps.changes.outputs.code == 'true'
        run: npm ci

      - name: Run lint
        if: steps.changes.outputs.code == 'true'
        run: npm run lint
