name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  lint:
    name: Linting
    uses: ./.github/workflows/lint.yml
    secrets: inherit

  src-tests:
    name: Backend Tests
    uses: ./.github/workflows/src-tests.yml
    secrets: inherit

  client-tests:
    name: Frontend Tests
    uses: ./.github/workflows/client-tests.yml
    secrets: inherit

  build:
    name: Docker Build
    needs: [lint, src-tests, client-tests]
    uses: ./.github/workflows/docker-build.yml
    secrets: inherit

  deploy:
    name: Deployment
    needs: [build]
    uses: ./.github/workflows/deploy.yml
    secrets: inherit