name: Semgrep

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  workflow_call:

jobs:
  semgrep:
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep:1.114
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            source:
              - 'src/**'
              - 'client/**'
              - '.github/workflows/semgrep.yml'
      - name: Run Semgrep
        if: steps.filter.outputs.source == 'true'
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
        run: semgrep ci
